services:
  postgres:
    image: postgres:17.6-alpine
    env_file:
      - ./example.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: on-failure
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./example.env
    restart: on-failure
    volumes:
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge